config/routes.rb
Sartor::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
    resources :appointment_contacts

    resources :profiles
    resources :simple_profiles
    resources :detailed_profiles
    resources :shirt_profiles

    resources :ja_giftsets

    get '/privacy', :to => "info#privacy"
    get '/terms', :to => "info#terms_of_service"
    get '/shipping', :to => "info#shipping"
    get '/returns', :to => "info#returns"
    get '/about_sartor', :to => "info#about_sartor"
    get '/perscholas', :to => "info#per_scholas"
    get '/mygift', :to => "info#mygift"

    get '/password/change' => 'user_passwords#edit', :as => :simple_edit_password

    post '/shirts-shirtconfig' => 'products#shirtConfigSession'
    get '/shirts' => 'products#index_shirts'
    post '/shirts-filter' => 'products#filtered_shirts'
    post '/shirts-tabs-click' => 'products#shirtresponse'
    post '/shirts-collections' => 'products#shirts_collections'
    post '/shirts-usual-style' => 'your_usual#add'
    get '/ties' => 'products#index_ties'

    get '/johnallans' => 'ja_giftsets#new'

    get '/products/show_no_tie'

    get '/gifting' => 'virtual_gift_cards#new'
    post '/gifting' => 'virtual_gift_cards#create'
    get  '/admin/users/virtual_gift_cards' => "admin/gift_cards#index", :as => :admin_virtual_gift_cards
    get  '/admin/users/:id/virtual_gift_cards/' => "admin/gift_cards#show", :as => :admin_virtual_gift_card
    post '/admin/users/redeem_gift_cards/' => "admin/gift_cards#redeem_gift_cards_complete"
    get '/admin/users/:id/redeem_gift_cards/' => "admin/gift_cards#redeem_gift_cards", :as => :admin_redeem_gift_cards
    post '/user/redeem-gift-cards' => 'users#redeem_gift_cards'

    put '/api/shipments/:id/update_item' => "api/shipments#update_item", :defaults => { :format => 'json' }
    get '/admin/orders/:id/detail_profile' => "admin/detailed_profiles#new"
    get '/admin/orders/:id/users/new' =>  "admin/users#new"
    get '/admin/orders/:id/show' => "admin/orders#show", :as => :show_admin_order
    put '/admin/orders/:id/show' => "admin/orders#show", :as => :show_admin_order_put
    put '/admin/orders/:id/save-jobs' =>  "admin/show_mockup#save_jobs_to_line_items"
    put '/admin/orders/:id/update-shirt-status' =>  "admin/show_mockup#update_shirt_status"
    put '/admin/orders/:id/add-tracking-number' =>  "admin/show_mockup#add_tracking_number"
    put '/api/shipments/:id/delete_line_item' => "api/shipments#delete_line_item", :defaults => {:format=>"json"}
    get '/admin/update-stocks' => "admin/stock_locations#update_stocks_for_all_products", :as => :update_stocks
    post '/admin/admin-get-measurements' => "admin/create_shirt#create_my_shirt"

    post '/admin/read_csv' => "admin/csv_uploaders#read_csv"
    get '/admin/csv/show' => "admin/csv_uploaders#show", :as => :admin_csv_show
    get '/admin/historical_orders' => "admin/historical_orders#show", :as => :admin_historical_orders_show
    post '/admin/historical_order_csv' => "admin/historical_orders#import_historical_orders"
    get '/admin/csv/notify' => "admin/csv_uploaders#notify", :as => :admin_import_notify
    
    get '/wishlist/refer_to_friend/:id' => "wishlist_mailer#email_form", :as => :wishlist_email_to_friend
    post '/wishlist/refer_to_friend/' => "wishlist_mailer#send_mail"
    post '/update_wished_products' => 'wished_products#update_wished_product'    

    get '/referral/referral_url_to_friend/:link' => "referral_mailer#email_form", :as => :referral_url_email_to_friend
    post '/referral/referral_url_to_friend/' => "referral_mailer#send_mail"

    get '/account/orders' => 'users#show_orders'
    get '/account/history' => 'users#show_history'
    get '/account/address' => 'users#show_address'
    get '/account/sartor-wardrobe' => 'users#sartor_wardrobe'
    get '/account/loyalty' => 'users#loyalty_points'
    get '/account/redeem' => 'users#redeem_cards'
    post '/shirt/wardrobe' => 'wardrobes#show', :as => :show_wardrobe

    get '/sartor_office' => 'appointment_contacts#sartor_office'
    get '/office_visit' => 'appointment_contacts#office_visit'

    get '/contact' => 'contact_us#show'
    post '/contact' => 'contact_us#create'

    get '/get-detailedProfile' => 'shirt_profiles#get_detailed_profile'
    post '/generate-measurements' => 'shirt_profiles#createnewmeasurements'

    post '/removeUnavailableLineItem' => 'orders#removeUnavailableLineItem'
    
    namespace :admin do
      resources :users do
        resources :profiles
        resources :detailed_profiles
        resources :shirt_profiles
        member do
          get 'invite'
        end
      end
    end
  end

end

app/views/spree/admin/users/_address_form.html.erb
<% s_or_b = type.chars.first %>

<div id="<%= type %>" data-hook="address_fields">
  <div class="field <%= "#{type}-row" %>">
    <%= f.label :firstname, Spree.t(:first_name) %>
    <%= f.text_field :firstname, :class => 'fullwidth' %>
  </div>

  <div class="field <%= "#{type}-row" %>">
    <%= f.label :lastname, Spree.t(:last_name) %>
    <%= f.text_field :lastname, :class => 'fullwidth' %>
  </div>

  <% if Spree::Config[:company] %>
    <div class="field <%= "#{type}-row" %>">
      <%= f.label :company, Spree.t(:company) %>
      <%= f.text_field :company, :class => 'fullwidth' %>
    </div>
  <% end %>

  <div class="field <%= "#{type}-row" %>">
    <%= f.label :address1, Spree.t(:street_address) %>
    <%= f.text_field :address1, :class => 'fullwidth' %>
  </div>

  <div class="field <%= "#{type}-row" %>">
    <%= f.label :address2, Spree.t(:street_address_2) %>
    <%= f.text_field :address2, :class => 'fullwidth' %>
  </div>

  <div class="field <%= "#{type}-row" %>">
    <%= f.label :city, Spree.t(:city) %>
    <%= f.text_field :city, :class => 'fullwidth' %>
  </div>

  <div class="field <%= "#{type}-row" %>">
    <%= f.label :zipcode, Spree.t(:zip) %>
    <%= f.text_field :zipcode, :class => 'fullwidth' %>
  </div>

  <div class="field <%= "#{type}-row" %>">
    <%= f.label :country_id, Spree.t(:country) %>
    <span id="<%= s_or_b %>country">
      <%= f.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'select2 fullwidth'} %>
    </span>
  </div>

  <div class="field <%= "#{type}-row" %>">
    <%= f.label :state_id, Spree.t(:state) %>
    <span id="<%= s_or_b %>state">
      <%= f.text_field :state_name,
            :style => "display: #{f.object.country.states.empty? ? 'block' : 'none' };",
           :disabled => !f.object.country.states.empty?, :class => 'fullwidth state_name' %>
      <%= f.collection_select :state_id, f.object.country.states.sort, :id, :name, {:include_blank => true}, {:class => 'select2 fullwidth', :style => "display: #{f.object.country.states.empty? ? 'none' : 'block' };", :disabled => f.object.country.states.empty?} %>
    </span>
  </div>

  <div class="field <%= "#{type}-row" %>">
    <%= f.label :phone, Spree.t(:phone) %>
    <%= f.phone_field :phone, :class => 'fullwidth' %>
  </div>
</div>

<% content_for :head do %>
  <%= javascript_tag do -%>
    $(document).ready(function(){
      $('span#<%= s_or_b %>country .select2').on('change', function() { update_state('<%= s_or_b %>'); });
    });
  <% end -%>
<% end %>

app/views/spree/admin/users/_addresses_form.html.erb
<div data-hook="bill_address_wrapper" class="alpha six columns">
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:billing_address) %></legend>
    <%= f.fields_for :bill_address, (@user.bill_address || Spree::Address.default(@user, "bill")) do |ba_form| %>
      <% ba_form.object ||= Spree::Address.new(country: Spree::Country.new) %>
      <%= render :partial => 'address_form', :locals => { :f => ba_form, :type => "billing" } %>
    <% end %>
  </fieldset>
</div>

<div data-hook="ship_address_wrapper" class="alpha six columns">
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:shipping_address) %></legend>
    <%= f.fields_for :ship_address, (@user.ship_address || Spree::Address.default(@user, "ship")) do |sa_form| %>
      <% sa_form.object ||= Spree::Address.new(country: Spree::Country.new) %>
      <%= render :partial => 'address_form', :locals => { :f => sa_form, :type => "shipping" } %>
    <% end %>
  </fieldset>
</div>

app/views/spree/admin/users/_form.html.erb
<div data-hook="admin_user_form_fields" class="row">
  <div class="alpha five columns">
     <%= f.field_container :email do %>
      <span style="color:red">*</span><%= f.label :email, Spree.t(:email) %>
      <%= f.email_field :email, :class => 'fullwidth' %>
      <%= error_message_on :user, :email %>
    <% end %>
    <%= f.field_container :first_name do %>
      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name, :class => 'fullwidth' %>
      <%= f.error_message_on :first_name %>
    <% end %>
    <%= f.field_container :last_name do %>
      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name, :class => 'fullwidth' %>
      <%= f.error_message_on :last_name %>
    <% end %>

    <div class="field">
      <%= label_tag nil, Spree.t(:roles) %>
      <ul>
        <% @roles.each do |role| %>
          <li>
            <%= check_box_tag 'user[spree_role_ids][]', role.id, @user.spree_roles.include?(role), :id => "user_spree_role_#{role.name}" %>
            <%= label_tag role.name %>
          </li>
        <% end %>
      </ul>
      <%= hidden_field_tag 'user[spree_role_ids][]', '' %>
    </div>

  </div>

  <div class="omega five columns">
    <%= f.field_container :password do %>
        <span style="color:red">*</span><%= f.label :password, Spree.t(:password) %>
      <%= f.password_field :password, :class => 'fullwidth' %>
      <%= f.error_message_on :password %>
    <% end %>

    <%= f.field_container :password do %>
        <span style="color:red">*</span><%= f.label :password_confirmation, Spree.t(:confirm_password) %>
      <%= f.password_field :password_confirmation, :class => 'fullwidth' %>
      <%= f.error_message_on :password_confirmation %>
    <% end %>
  </div>
</div>

app/views/spree/admin/users/_redeem_gift_cards_sidebar.html.erb
<li<%== ' class="active"' if current == :gift_cards %>>
  <%= link_to_with_icon 'money', Spree.t(:"admin.user.gift_cards"), admin_virtual_gift_card_path(@user) %>
</li>

<li<%== ' class="active"' if current == :redeem_gift_cards %>>
  <%= link_to_with_icon 'money', Spree.t(:"admin.user.redeem_gift_cards"), admin_redeem_gift_cards_path(@user) %>
</li>

app/views/spree/admin/users/_sub_menu.html.erb
<% if request.fullpath.match(/^\/admin\/users/) %>
  <% content_for :sub_menu do %>
    <ul id="sub_nav" class="inline-menu">
      <%= tab :users %>
      <%= tab :virtual_gift_cards, :match_path => '/users/gift_cards' %>
    </ul>
  <% end %>
<% end %>

app/views/spree/admin/users/edit.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render :partial => 'spree/admin/users/sidebar', :locals => { :current => :account } %>
<% content_for :page_actions do %>
	<% if !@user.last_sign_in_at %>
		<li> <%= button_link_to "Send Invite Email", spree.invite_admin_user_path(@user) %> </li>
	<% end %>
  <li>
    <%= button_link_to Spree.t(:show), '/admin/users/' + @user.id.to_s, :icon => '' %>
    <%= button_link_to Spree.t(:back_to_users_list), spree.admin_users_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<fieldset data-hook="admin_user_edit_general_settings" class="alpha twelve columns">
  <legend><%= Spree.t(:general_settings) %></legend>

  <div data-hook="admin_user_edit_form_header">
    <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>
  </div>

  <div data-hook="admin_user_edit_form">
    <%= form_for [:admin, @user], as: :user, url: admin_user_url(@user), method: :put do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div data-hook="admin_user_edit_form_button">
        <%= render :partial => 'spree/admin/shared/edit_resource_links', :locals => { :collection_url => admin_users_url } %>
      </div>
    <% end %>
  </div>
</fieldset>

<hr/>
<br/>
<div class="form-buttons filter-actions actions" data-hook="buttons">
	<%= link_to_with_icon('icon-plus', "New Detailed Profile", new_admin_user_detailed_profile_url(@user), :id => 'new_detailed_profile_link', :class => 'button') %>
	<%= link_to_with_icon('icon-plus', "New Shirt Profile", new_admin_user_shirt_profile_url(@user), :id => 'new_shirt_profile_link', :class => 'button') %>
</div>
<br/>

<div>
  <table>
    <% @user.profiles.each do |profile_pred| %>
      <tr>
        <% profile = profile_pred.heir %>
        <td><%= profile.name %></td>
        <td>
           Created at: <%= profile.created_at %><br/>
           Updated at: <%= profile.updated_at %>
        </td>
        <td>
           <%= profile.predecessor.heir_type %><br/>
        </td>
		<td class="actions">
		<%= link_to_with_icon 'icon-edit', t(:edit), edit_admin_user_profile_url(@user, profile_pred), :no_text => true, :data => {:action => 'edit'} %>
		<%= link_to_delete profile, { :url => admin_user_profile_url(@user, profile_pred), :no_text => true } %>
		</td>
      </tr>
    <% end %>
  </table>
</div>

<fieldset>
<legend>Your Usual Configuration </legend>
   <div class="right six columns alpha">
    <%= label :collar_code, "Default Collar" %>
    <%= select_tag :collar_code, options_from_collection_for_select(ShirtConfiguration::COLLARS, :first, :last,if  @usual_shirt_configuration != nil
                              @usual_shirt_configuration.collar_code
                              else
                               0
                              end),:style => "width:100%"%><br/>

      <%= label :cuff_code, "Default Cuffs" %>
    <%= select_tag :cuff_code, options_from_collection_for_select(ShirtConfiguration::CUFFS, :first, :last,if  @usual_shirt_configuration != nil
                          @usual_shirt_configuration.cuff_code
                          else
                           0
                          end),:style => "width:100%" %><br/>
      <%= label :pocket_code, "Default Pockets" %>
    <%= select_tag :pocket_code, options_from_collection_for_select(ShirtConfiguration::POCKETS, :first, :last,if  @usual_shirt_configuration != nil
                              @usual_shirt_configuration.pocket_code
                              else
                               0
                              end),:style => "width:100%" %>

    </div>
    <div class="right six columns omega">
      <%= label :button_code, "Default Buttons" %>
    <%= select_tag :button_code, options_from_collection_for_select(ShirtConfiguration::BUTTONS, :first, :last, if @usual_shirt_configuration != nil
                               @usual_shirt_configuration.button_code
                               else
                                0
                               end),:style => "width:100%" %><br/>
    </div>
     <div class="right six columns omega">
        <%= label :placket_code, "Default plackets" %>
      <%= select_tag :placket_code, options_from_collection_for_select(ShirtConfiguration::PLACKETS, :first, :last, if @usual_shirt_configuration != nil
                                 @usual_shirt_configuration.placket_code
                                 else
                                  0
                                 end),:style => "width:100%" %><br/>
    </div>
  <div class="right twelve columns form-buttons actions filter-actions">
    <button onclick="saveYourUsual(<%= @user_id %>)" class="fa fa-refresh button sub-link">
    Update</button>
  </div>
</fieldset>

<fieldset data-hook="admin_user_api_key" id="admin_user_edit_api_key" class="alpha twelve columns">
  <legend><%= Spree.t('access', :scope => 'api') %></legend>

  <% if @user.spree_api_key.present? %>
    <div class="field">
      <div id="current-api-key"><%= Spree.t('key', :scope => 'api') %>: <%= @user.spree_api_key %></div>
    </div>
    <div class="filter-actions actions">
      <%= form_tag spree.clear_api_key_admin_user_path(@user), :method => :put do %>
        <%= button Spree.t('clear_key', :scope => 'api'), 'trash' %>
      <% end %>

      <span class="or"><%= Spree.t(:or)%></span>

      <%= form_tag spree.generate_api_key_admin_user_path(@user), :method => :put do %>
        <%= button Spree.t('regenerate_key', :scope => 'api'), 'refresh' %>
      <% end %>
    </div>

  <% else %>

    <div class="no-objects-found"><%= Spree.t('no_key', :scope => 'api') %></div>

    <div class="filter-actions actions">
      <%= form_tag spree.generate_api_key_admin_user_path(@user), :method => :put do %>
        <%= button Spree.t('generate_key', :scope => 'api'), 'key' %>
      <% end %>
    </div>
  <% end %>
</fieldset>

app/views/spree/admin/users/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_users) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_user), new_admin_user_url, :icon => 'plus', :id => 'admin_new_user_link' %>
  </li>
<% end %>

<table class="index" id="listing_users" data-hook>
  <thead>
    <tr data-hook="admin_users_index_headers">
		<th><%= sort_link @search,:email, Spree.t(:user), {}, {:title => 'users_email_title'} %></th>
		<th>Name</th>
		<th>Profiles</th>
		<th>Created</th>
		<th>Sign In</th>
		<th>Invited</th>
      <th data-hook="admin_users_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user|%>
      <% if user %>
       <!-- Need to fix  data-hook="admin_users_index_rows" class="  cycle('odd', 'even') " -->
          <tr id="<%= spree_dom_id user %>">
            <td class='user_email'><%=link_to user.email, edit_admin_user_url(user) %></td>
    				<td class='user_name'><%=user.last_name %>, <%=user.first_name %></td>
    				<td><%= user.profiles ? user.profiles.count : "" %></td>
    				<td><%=user.created_at %></td>
    				<td><%=user.current_sign_in_at || user.last_sign_in_at %></td>
    				<td><%=user.invite_sent_at %></td>
            <td data-hook="admin_users_index_row_actions" class="actions">
              <%= link_to_edit user, :no_text => true %>
              <%= link_to_delete user, :no_text => true %>
            </td>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

<% content_for :sidebar_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :sidebar do %>
  <div class="box align-center" data-hook="admin_users_index_search">
    <%= search_form_for [:admin, @search], url: admin_users_url do |f| %>
      <div class="field">
        <%= f.label Spree.t(:email) %> <br>
        <%= f.text_field :email_cont, :class => 'fullwidth' %>
      </div>
      <div data-hook="admin_users_index_search_buttons">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/users/new.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:new_user) %>
<% end %>

<% content_for :page_actions do %>
    <li>
      <%= button_link_to Spree.t(:back_to_users_list), spree.admin_users_path, :icon => 'arrow-left' %>
    </li>
<% end %>

<div data-hook="admin_user_new_form_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>
</div>

<div data-hook="admin_user_new_form">
  <%= form_for [:admin, @user], url: admin_users_url(:order_id=>@orderID), method: :post do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div data-hook="admin_user_new_form_buttons">
        <%= render :partial => 'spree/admin/shared/new_resource_links' %>
      </div>
  <% end %>
</div>

app/views/spree/admin/users/show.html.erb
<% content_for :page_title do %>
  <%= link_to "#{@user.email}", edit_admin_user_url(@user) %>
<% end %>
<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_users_list), spree.admin_users_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<label>
	<h3>
		<%= @user.first_name %> <%= @user.last_name %>
	</h3>
</label>

<div data-hook='admin_user_show_roles'></div>