config/routes.rb
Sartor::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
    resources :appointment_contacts

    resources :profiles
    resources :simple_profiles
    resources :detailed_profiles
    resources :shirt_profiles

    resources :ja_giftsets

    get '/privacy', :to => "info#privacy"
    get '/terms', :to => "info#terms_of_service"
    get '/shipping', :to => "info#shipping"
    get '/returns', :to => "info#returns"
    get '/about_sartor', :to => "info#about_sartor"
    get '/perscholas', :to => "info#per_scholas"
    get '/mygift', :to => "info#mygift"

    get '/password/change' => 'user_passwords#edit', :as => :simple_edit_password

    post '/shirts-shirtconfig' => 'products#shirtConfigSession'
    get '/shirts' => 'products#index_shirts'
    post '/shirts-filter' => 'products#filtered_shirts'
    post '/shirts-tabs-click' => 'products#shirtresponse'
    post '/shirts-collections' => 'products#shirts_collections'
    post '/shirts-usual-style' => 'your_usual#add'
    get '/ties' => 'products#index_ties'

    get '/johnallans' => 'ja_giftsets#new'

    get '/products/show_no_tie'

    get '/gifting' => 'virtual_gift_cards#new'
    post '/gifting' => 'virtual_gift_cards#create'
    get  '/admin/users/virtual_gift_cards' => "admin/gift_cards#index", :as => :admin_virtual_gift_cards
    get  '/admin/users/:id/virtual_gift_cards/' => "admin/gift_cards#show", :as => :admin_virtual_gift_card
    post '/admin/users/redeem_gift_cards/' => "admin/gift_cards#redeem_gift_cards_complete"
    get '/admin/users/:id/redeem_gift_cards/' => "admin/gift_cards#redeem_gift_cards", :as => :admin_redeem_gift_cards
    post '/user/redeem-gift-cards' => 'users#redeem_gift_cards'

    put '/api/shipments/:id/update_item' => "api/shipments#update_item", :defaults => { :format => 'json' }
    get '/admin/orders/:id/detail_profile' => "admin/detailed_profiles#new"
    get '/admin/orders/:id/users/new' =>  "admin/users#new"
    get '/admin/orders/:id/show' => "admin/orders#show", :as => :show_admin_order
    put '/admin/orders/:id/show' => "admin/orders#show", :as => :show_admin_order_put
    put '/admin/orders/:id/save-jobs' =>  "admin/show_mockup#save_jobs_to_line_items"
    put '/admin/orders/:id/update-shirt-status' =>  "admin/show_mockup#update_shirt_status"
    put '/admin/orders/:id/add-tracking-number' =>  "admin/show_mockup#add_tracking_number"
    put '/api/shipments/:id/delete_line_item' => "api/shipments#delete_line_item", :defaults => {:format=>"json"}
    get '/admin/update-stocks' => "admin/stock_locations#update_stocks_for_all_products", :as => :update_stocks
    post '/admin/admin-get-measurements' => "admin/create_shirt#create_my_shirt"

    post '/admin/read_csv' => "admin/csv_uploaders#read_csv"
    get '/admin/csv/show' => "admin/csv_uploaders#show", :as => :admin_csv_show
    get '/admin/historical_orders' => "admin/historical_orders#show", :as => :admin_historical_orders_show
    post '/admin/historical_order_csv' => "admin/historical_orders#import_historical_orders"
    get '/admin/csv/notify' => "admin/csv_uploaders#notify", :as => :admin_import_notify
    
    get '/wishlist/refer_to_friend/:id' => "wishlist_mailer#email_form", :as => :wishlist_email_to_friend
    post '/wishlist/refer_to_friend/' => "wishlist_mailer#send_mail"
    post '/update_wished_products' => 'wished_products#update_wished_product'    

    get '/referral/referral_url_to_friend/:link' => "referral_mailer#email_form", :as => :referral_url_email_to_friend
    post '/referral/referral_url_to_friend/' => "referral_mailer#send_mail"

    get '/account/orders' => 'users#show_orders'
    get '/account/history' => 'users#show_history'
    get '/account/address' => 'users#show_address'
    get '/account/sartor-wardrobe' => 'users#sartor_wardrobe'
    get '/account/loyalty' => 'users#loyalty_points'
    get '/account/redeem' => 'users#redeem_cards'
    post '/shirt/wardrobe' => 'wardrobes#show', :as => :show_wardrobe

    get '/sartor_office' => 'appointment_contacts#sartor_office'
    get '/office_visit' => 'appointment_contacts#office_visit'

    get '/contact' => 'contact_us#show'
    post '/contact' => 'contact_us#create'

    get '/get-detailedProfile' => 'shirt_profiles#get_detailed_profile'
    post '/generate-measurements' => 'shirt_profiles#createnewmeasurements'

    post '/removeUnavailableLineItem' => 'orders#removeUnavailableLineItem'
    
    namespace :admin do
      resources :users do
        resources :profiles
        resources :detailed_profiles
        resources :shirt_profiles
        member do
          get 'invite'
        end
      end
    end
  end

end

app/models/detailed_profile.rb
class DetailedProfile < ActiveRecord::Base
  acts_as_heir_of :profile

  FITS = [
    'extra slim',
    'slim',
    'Regular',
    'Classic'
  ]

  attr_accessor :Generator_Fit
  @Generator_Fit = "slim"
  attr_accessor :Body_Profile_Unit
  Body_Profile_Unit = "inch"

  MINIMUM_HIP_ALLOWANCE_MULTIPLER = 0.8
  HIP_ALLOWANCE_MULTIPLER_FLARE_THRESHOLD = 0.75
  UNTUCKED_WAIST_HIP_MAX_RATIO = 0.5
  MIDTUCK_WIST_HIP_MAX_RATIO = 0.75
  BICEP_CHEST_DEFAULT_RATIO = 0.32

  # FIXED ALLOWANCES CONSTANTS
  CUFF_ALLOWANCE_INCH = 1.75
  COLLAR_ALLOWANCE_INCH = 0.5
  SLEEVE_ALLOWANCE_INCH = 0.75

  # ALLOWANCE FUNCTIONS
  def torso_allowance
    case @Generator_Fit
      when "extra slim"
        allowance = (chest - 38) * 0.05 + 3
      when "slim"
        allowance = (chest - 38) * 0.08 + 3.5
    end
   allowance
  end

  def bicep_allowance
    case @Generator_Fit
      when "extra slim"
        allowance = 1.6
      when "slim"
        allowance = 2.4
      when "Regular"
        allowance = 3.5
      when "Classic"
        allowance = 4.5
    end
    allowance
  end

  def max_hip_flare
    case @Generator_Fit
      when "extra slim"
        max_flare = 0.14
      when "slim"
        max_flare = 0.12
      when "Regular"
        max_flare = 0.10
      when "Classic"
        max_flare = 0.10
    end
    max_flare
  end

  # FIXED ALLOWANCE GETTERS
  def shirt_cuff
    profile_is_inches ? round_quarter(wrist + CUFF_ALLOWANCE_INCH) : wrist + inches_to_cm(CUFF_ALLOWANCE_INCH)
  end

  def shirt_collar
    profile_is_inches ? round_quarter(neck + COLLAR_ALLOWANCE_INCH) : collar + inches_to_cm(COLLAR_ALLOWANCE_INCH)
  end

  def shirt_sleeve
    profile_is_inches ? round_quarter(sleeve + SLEEVE_ALLOWANCE_INCH) : sleeve + inches_to_cm(SLEEVE_ALLOWANCE_INCH)
  end

  def shirt_shoulder
    profile_is_inches ? round_quarter(yoke) : yoke
  end

  def shirt_length
    profile_is_inches ? round_quarter(length) : length
  end

  # BICEP ALLOWANCE GETTER
  def shirt_bicep
    bicep_allowance_method = bicep + bicep_allowance
    chest_multiplier_method = BICEP_CHEST_DEFAULT_RATIO * shirt_chest
    round_quarter([bicep_allowance_method, chest_multiplier_method].max)
  end

  # TORSO ALLOWANCE GETTERS
  # added to_f to handle nil condition
  def shirt_chest
    shirt = profile_is_inches ? round_quarter(chest + torso_allowance.to_f) : chest + inches_to_cm(torso_allowance.to_f)
  end

  def shirt_waist
    waist_allowance_method = waist + torso_allowance.to_f
    base_hip_plus_allowance = hip + torso_allowance.to_f
    min_waist_tucked = base_hip_plus_allowance / (1 + max_hip_flare)
    round_quarter([waist_allowance_method, min_waist_tucked].max)
  end

  def shirt_hip
    base_hip_plus_allowance = hip + torso_allowance.to_f
    profile_is_inches ? round_quarter(hip + torso_allowance.to_f) : hip + inches_to_cm(torso_allowance.to_f)
  end


  # UTILITY FUNCTIONS
  def inches_to_cm (measurement)
    measurement * 2.54
  end

  def profile_is_inches
    Body_Profile_Unit == "inch"
  end

  def round_quarter (measurement)
    (4 * measurement).round.to_d / 4
  end

  # attr_accessible :name, :embroidery_name, :height_ft, :height_in, :weight, :default_fit, :neck, :yoke, :sleeve, :chest, :waist, :hip, :length, :length_untucked, :bicep, :wrist, :wrist_watch, :watch_hand
    validates :name, presence: {:message => "Measurement name can not be blank" }
    validates :neck, presence: {:message => "Neck can not be blank" }
    validates :yoke, presence: {:message => "Yoke can not be blank" }
    validates :sleeve, presence: {:message => "Sleeve can not be blank" }
    validates :chest, presence: {:message => "Chest can not be blank" }
    validates :waist, presence: {:message => "Chest can not be blank" }
    validates :hip, presence: {:message => "Hip can not be blank" }
    validates :bicep, presence: {:message => "Bicep can not be blank" }
    validates :wrist, presence: {:message => "Wrist can not be blank" }
    validates :length, presence: {:message => "Tucked Length can not be blank" }
    validates :length_untucked, presence: {:message => "Untucked length can not be blank" }
end

app/controllers/spree/admin/detailed_profiles_controller.rb
module Spree
  module Admin
    class DetailedProfilesController < Spree::Admin::ProfilesController

      def index
        @profiles = @user.profiles
        respond_with(@profiles)
      end

      def new
        # load default historic profile 
        if Profile.where(:user_id=> params[:user_id],:heir_type => 'DetailedProfile').length > 0
          @historic_profile = Profile.where(:user_id => params[:user_id], :heir_type => 'DetailedProfile').order("created_at DESC").first
        end
        @orderID = params[:id]
        @profile = DetailedProfile.new
        @profile.name = spree_current_user.first_name + spree_current_user.last_name
      end

      def create
        orderID = params[:order_id]

        if Profile.where(:user_id=> params[:user_id],:heir_type => 'DetailedProfile').length > 0
          @historic = Profile.where(:user_id => params[:user_id], :heir_type => 'DetailedProfile').order("created_at DESC").first
           if @historic.heir.update(detailed_profile_params) 
            flash[:success] = 'Measurement profile successfully updated.'
           end
        else
          @profile = DetailedProfile.new
          update_attributes(@profile)
          @profile.predecessor.user = @user
          @profile.name = spree_current_user.first_name + spree_current_user.last_name
          if @profile.save
            flash[:success] = 'Measurement profile successfully created.'
          end
        end


        if session[:urlorder]
              redirect_to session[:urlorder]
        elsif(orderID != nil)
          redirect_to edit_admin_order_url(@order, :id => orderID)
        else
          redirect_to spree.edit_polymorphic_url([:admin, @user])
        end


      end

      def show
        @profile = Profile.find(params[:id])
      end

      def edit
        # TODO handle not found case?
        @profile = Profile.find(params[:id])
        @profile = @profile.heir
      end

      def update
        profile = Profile.find(params[:id])
        detailed_profile= profile.heir
        if update_attributes(detailed_profile)
          #todo: I18n for resource name
          flash[:notice] = "Measurement profile successfully updated"
        end
        redirect_to spree.edit_polymorphic_url([:admin, @user])
      end

      def destroy
        @profile = Profile.find(params[:id])
        if @profile.destroy
           #todo: I18n for resource name
          flash[:notice] = "Measurement profile successfully removed"
          respond_with(@profile) do |format|
            format.html {  redirect_to spree.polymorphic_url([:admin, @user, model_class]) }
            format.js   { render :partial => "spree/admin/shared/destroy" }
          end
        else
          invoke_callbacks(:destroy, :fails)
          respond_with(@profile) do |format|
            format.html {  redirect_to spree.polymorphic_url([:admin, @user, model_class]) }
          end
        end
      end

      def update_attributes(profile)
        profile.update_attributes(detailed_profile_params)
      end

      def detailed_profile_params
        params.require(:detailed_profile).permit(:name, :embroidery_name, :height_ft, :height_in, :weight, :neck, :yoke, :sleeve, :chest, :waist, :hip, :length, :bicep, :wrist, :length_untucked, :wrist_watch, :watch_hand, :default_fit_code, :default_length_code)
      end
    end
  end
end

app/controllers/spree/detailed_profiles_controller.rb
class Spree::DetailedProfilesController < Spree::ProfilesController
  ssl_required

  def new_profile
    profile = DetailedProfile.new
    profile.default_fit_code = 1 # Slim; see ShirtConfiguration::FITS
    @showdeleteButton = false;
    profile
  end

  def update
    if update_attributes(@detailed_profile)
      #todo: I18n for resource name
      flash[:notice] = "Successfully Updated"
    end
    if (params['_stay_in'] == 'edit')
      redirect_to profiles_path(@detailed_profile.predecessor)
    else
      redirect_to profiles_path
    end
  end

  def destroy
    @detailed_profile.destroy
       #todo: I18n for resource name
       flash[:notice] = "Successfully Removed"
    redirect_to profiles_path
  end

  def show
    # TODO handle not found case?
    @profile = @profile.heir
    session[:return_to] ||= request.referer  # store referrer so we can go back to the page
    render "spree/detailed_profiles/show"
  end

  def update_attributes(profile)
    profile.update_attributes(detailed_profile_params)
  end

  def detailed_profile_params
    params.require(:profile).permit(:name, :embroidery_name, :default_fit_code, :height_ft, :height_in, :weight, :neck, :yoke, :sleeve, :chest, :waist, :hip, :length, :bicep, :wrist, :wrist_watch, :watch_hand, :length, :length_untucked, :default_length_code)
  end

end

app/views/spree/admin/detailed_profiles/_form.html.erb
  <div class="row">
    <div class=" omega eight columns">
      <div class=" omega six columns">
        <%= f.label :name, Spree.t(:'Wearer’s Name'), class:"omega five columns"%>
        <%= f.text_field :name, class:" omega five columns",:value=> @historic_profile ? @historic_profile.name : ""%>
      </div>
      <div class=" omega six columns">
        <%= f.label :neck, Spree.t(:neck), class:" omega five columns"%>
    <%= f.number_field :neck, class:" omega five columns" ,:step => ".125",:value=> @historic_profile ? @historic_profile.heir.neck : 0 %>
      </div>
  	  <div class=" omega six columns">
        <%= f.label :yoke, Spree.t(:shoulder), class:" omega five columns"%>
        <%= f.number_field :yoke, class:" omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.yoke : 0%>
      </div>
      <div class=" omega six columns">
        <%= f.label :sleeve, Spree.t(:sleeve), class:" omega five columns"%>
        <%= f.number_field :sleeve, class:" omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.sleeve : 0 %>
      </div>
  		<div class=" omega six columns">
  			<%= f.label :yoke, Spree.t(:bicep), class:" omega five columns"%>
  			<%= f.number_field :bicep, class:" omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.bicep : 0 %>
  		</div>
      <div class=" omega six columns">
        <%= f.label :wrist, Spree.t(:wrist), class:" omega five columns"%>
        <%= f.number_field :wrist, class:" omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.wrist : 0 %>
      </div>
       <div class=" omega six columns">
        <%= f.label :wrist_watch, Spree.t(:wrist_watch), class:" omega five columns"%>
        <%= f.number_field :wrist_watch, class:"omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.wrist_watch : 0%>
      </div>
      <div class=" omega six columns">
        <%= f.label :watch_hand, Spree.t(:on_hand), class:" omega five columns"%>
        <%= f.select :watch_hand, Profile::WATCH_HANDS, {:selected=>@historic_profile ? @historic_profile.heir.watch_hand : 'None'}, { class: 'input-small input-sm form-control omega five columns'}%>
      </div>
    </div>
    <div class=" omega eight columns">
      <div class="omega six columns">
        <%= f.label :height_ft, "HEIGHT (FT)", class:" omega five columns"%>
        <%= f.select :height_ft, Profile::HEIGHTS_FT, {:selected=>@historic_profile ? @historic_profile.height_ft : 4}, {class:" omega five columns"} %>
      </div>
      <div class=" omega six columns">
        <%= f.label :height_in, "HEIGHT (IN)", class:" omega five columns"%>
        <%= f.select :height_in, Profile::HEIGHTS_IN, {:selected=>@historic_profile ? @historic_profile.height_in : 0}, {class:" omega five columns"}  %>
      </div>
      <div class=" omega six columns">
        <%= f.label :weight, Spree.t(:weight), class:" omega five columns"%>
        <%= f.number_field :weight, class:" omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.weight : 0%>
      </div>
      <div class=" omega six columns">
        <%= f.label :yoke, Spree.t(:chest), class:" omega five columns"%>
        <%= f.number_field :chest, class:" omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.chest : 0 %>
      </div>
    	<div class=" omega six columns">
    		<%= f.label :waist, Spree.t(:waist), class:" omega five columns"%>
    		<%= f.number_field :waist, class:" omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.waist : 0 %>
    	</div>
      <div class=" omega six columns">
      	<%= f.label :hip, Spree.t(:seat), class:" omega five columns"%>
      	<%= f.number_field :hip, class:"omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.hip : 0 %>
      </div>
      <div class=" omega six columns">
        <%= f.label :length, Spree.t(:length_tucked), class:" omega five columns"%>
        <%= f.number_field :length, class:"omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.length : 0%>
      </div>
      <div class=" omega six columns">
        <%= f.label :length_untucked, Spree.t(:length_untucked), class:" omega five columns"%>
        <%= f.number_field :length_untucked, class:"omega five columns" ,:step => ".125",:value=>@historic_profile ? @historic_profile.heir.length_untucked : 0 %>
      </div>
    </div>
    <% if session[:urlorder] %>
    <div class=" omega sixteen columns" style="text-align:center;">
    <br/>
     <div class=" omega two columns">
       <button href="<%= session[:urlorder]%>" >Go Back</button>
     </div>
    </div>
    <% end %>
  </div>

app/views/spree/admin/detailed_profiles/edit.html.erb
<% content_for :page_title do %>
  Editing Body Measurement Profile
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to "User Settings", edit_admin_user_url(@profile.user), :icon => 'icon-arrow-left' %>
  </li>
<% end %>


<div>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>
</div>

<%= simple_form_for [@user, @profile], :url => admin_user_detailed_profile_path do |f| %>
 <fieldset>
   <legend align="center"><%= @profile.name %></legend>
     <%= render :partial => 'spree/admin/detailed_profiles/form', :locals => { :f => f } %>
   </div>

	<div class="form-buttons filter-actions actions" data-hook="buttons">
	  <%= button t(:update), 'icon-refresh' %>
	  <span class="or"><%= t(:or) %></span>
	  <%= link_to t(:cancel), edit_admin_user_url(@profile.user), :id => 'cancel_link', :class => 'button icon-remove' %>
	</div>
 </fieldset>
<% end %>

app/views/spree/admin/detailed_profiles/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  Profiles
<% end %>

<% content_for :page_actions do %>
  <li id="new_profile_link">
    <%= button_link_to "New Profile", new_admin_user_detailed_profile_url(@user), { :remote => true, :icon => 'icon-plus', :id => 'new_profile_link' } %>
  </li>
<% end %>
User: <%= "#{@user.last_name}, #{@user.first_name}" %>

<table class="index" id="listing_users" data-hook>
  <colgroup>
    <col style="width: 85%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr>
      <th>Profile Name</th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile|%>
      <tr id="<%= spree_dom_id profile %>" class="<%= cycle('odd', 'even')%>">
        <td><%=link_to profile.name, admin_user_detailed_profile_url(@user, profile) %></td>
        <td class="actions">
          <%#= link_to_edit profile, :no_text => true %>
          <%#= link_to_delete profile, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/detailed_profiles/new.html.erb
    <%= simple_form_for [@user, @profile], :url => admin_user_detailed_profiles_path(@user, :order_id=>@orderID) do |f| %>
  <fieldset>
    <legend align="center">New Body Measurement Profile</legend>

      <%= render :partial => 'spree/admin/detailed_profiles/form', :locals => { :f => f } %>

      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button t(:update), 'icon-refresh' %>
        <span class="or"><%= t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', t(:cancel), edit_admin_user_url(@user), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>

app/views/spree/admin/detailed_profiles/show.html.erb
<% content_for :page_title do %>
  Measurement Profile
<% end %>

<table>
  <tr>
    <th>Name</th>
    <td>
      <%= @profile.name %>
    </td>
  </tr>
	<tr>
		<th>Created at</th>
		<td>
			<%= @profile.created_at %>
		</td>
	</tr>
	<tr>
		<th>Updated at</th>
		<td>
			<%= @profile.updated_at %>
		</td>
	</tr>
	<tr>
		<th>Height</th>
		<td>
			<%= @profile.height_ft %>' <%= @profile.height_in %>"
		</td>
	</tr>
	<tr>
		<th>Weight</th>
		<td>
			<%= @profile.weight %>
		</td>
	</tr>
	<tr>
		<th>Neck</th>
		<td>
		<%= @profile.neck %>
		</td>
	</tr>
	<tr>
		<th>Shoulder</th>
		<td>
		<%= @profile.yoke %>
		</td>
	</tr>
	<tr>
		<th>Sleeve</th>
		<td>
			<%= @profile.sleeve %>
		</td>
	</tr>
	<tr>
		<th>Chest</th>
		<td>
		<%= @profile.chest %>
		</td>
	</tr>
	<tr>
		<th>Waist</th>
		<td>
		<%= @profile.waist %>
		</td>
	</tr>
	<tr>
		<th>Hip</th>
		<td>
		<%= @profile.hip %>
		</td>
	</tr>
	<tr>
		<th>Length</th>
		<td>
		<%= @profile.length %>
		</td>
	</tr>
	<tr>
		<th>Length - Untucked</th>
		<td>
		<%= @profile.length_untucked %>
		</td>
	</tr>
	<tr>
		<th>Bicep</th>
		<td>
		<%= @profile.bicep %>
		</td>
	</tr>
	<tr>
		<th>Wrist</th>
		<td>
		<%= @profile.wrist %>
		</td>
	</tr>
	<tr>
		<th>Wrist - Watch</th>
		<td>
		<%= @profile.wrist_watch %>
		</td>
	</tr>
	<tr>
		<th>Watch Hand</th>
		<td>
		<%= @profile.watch_hand %>
		</td>
	</tr>
	<tr>
		<th>Fit</th>
		<td>
		<%= @profile.default_fit %>
		</td>
	</tr>
</table>