config/routes.rb
Sartor::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
    resources :appointment_contacts

    resources :profiles
    resources :simple_profiles
    resources :detailed_profiles
    resources :shirt_profiles

    resources :ja_giftsets

    get '/privacy', :to => "info#privacy"
    get '/terms', :to => "info#terms_of_service"
    get '/shipping', :to => "info#shipping"
    get '/returns', :to => "info#returns"
    get '/about_sartor', :to => "info#about_sartor"
    get '/perscholas', :to => "info#per_scholas"
    get '/mygift', :to => "info#mygift"

    get '/password/change' => 'user_passwords#edit', :as => :simple_edit_password

    post '/shirts-shirtconfig' => 'products#shirtConfigSession'
    get '/shirts' => 'products#index_shirts'
    post '/shirts-filter' => 'products#filtered_shirts'
    post '/shirts-tabs-click' => 'products#shirtresponse'
    post '/shirts-collections' => 'products#shirts_collections'
    post '/shirts-usual-style' => 'your_usual#add'
    get '/ties' => 'products#index_ties'

    get '/johnallans' => 'ja_giftsets#new'

    get '/products/show_no_tie'

    get '/gifting' => 'virtual_gift_cards#new'
    post '/gifting' => 'virtual_gift_cards#create'
    get  '/admin/users/virtual_gift_cards' => "admin/gift_cards#index", :as => :admin_virtual_gift_cards
    get  '/admin/users/:id/virtual_gift_cards/' => "admin/gift_cards#show", :as => :admin_virtual_gift_card
    post '/admin/users/redeem_gift_cards/' => "admin/gift_cards#redeem_gift_cards_complete"
    get '/admin/users/:id/redeem_gift_cards/' => "admin/gift_cards#redeem_gift_cards", :as => :admin_redeem_gift_cards
    post '/user/redeem-gift-cards' => 'users#redeem_gift_cards'

    put '/api/shipments/:id/update_item' => "api/shipments#update_item", :defaults => { :format => 'json' }
    get '/admin/orders/:id/detail_profile' => "admin/detailed_profiles#new"
    get '/admin/orders/:id/users/new' =>  "admin/users#new"
    get '/admin/orders/:id/show' => "admin/orders#show", :as => :show_admin_order
    put '/admin/orders/:id/show' => "admin/orders#show", :as => :show_admin_order_put
    put '/admin/orders/:id/save-jobs' =>  "admin/show_mockup#save_jobs_to_line_items"
    put '/admin/orders/:id/update-shirt-status' =>  "admin/show_mockup#update_shirt_status"
    put '/admin/orders/:id/add-tracking-number' =>  "admin/show_mockup#add_tracking_number"
    put '/api/shipments/:id/delete_line_item' => "api/shipments#delete_line_item", :defaults => {:format=>"json"}
    get '/admin/update-stocks' => "admin/stock_locations#update_stocks_for_all_products", :as => :update_stocks
    post '/admin/admin-get-measurements' => "admin/create_shirt#create_my_shirt"

    post '/admin/read_csv' => "admin/csv_uploaders#read_csv"
    get '/admin/csv/show' => "admin/csv_uploaders#show", :as => :admin_csv_show
    get '/admin/historical_orders' => "admin/historical_orders#show", :as => :admin_historical_orders_show
    post '/admin/historical_order_csv' => "admin/historical_orders#import_historical_orders"
    get '/admin/csv/notify' => "admin/csv_uploaders#notify", :as => :admin_import_notify
    
    get '/wishlist/refer_to_friend/:id' => "wishlist_mailer#email_form", :as => :wishlist_email_to_friend
    post '/wishlist/refer_to_friend/' => "wishlist_mailer#send_mail"
    post '/update_wished_products' => 'wished_products#update_wished_product'    

    get '/referral/referral_url_to_friend/:link' => "referral_mailer#email_form", :as => :referral_url_email_to_friend
    post '/referral/referral_url_to_friend/' => "referral_mailer#send_mail"

    get '/account/orders' => 'users#show_orders'
    get '/account/history' => 'users#show_history'
    get '/account/address' => 'users#show_address'
    get '/account/sartor-wardrobe' => 'users#sartor_wardrobe'
    get '/account/loyalty' => 'users#loyalty_points'
    get '/account/redeem' => 'users#redeem_cards'
    post '/shirt/wardrobe' => 'wardrobes#show', :as => :show_wardrobe

    get '/sartor_office' => 'appointment_contacts#sartor_office'
    get '/office_visit' => 'appointment_contacts#office_visit'

    get '/contact' => 'contact_us#show'
    post '/contact' => 'contact_us#create'

    get '/get-detailedProfile' => 'shirt_profiles#get_detailed_profile'
    post '/generate-measurements' => 'shirt_profiles#createnewmeasurements'

    post '/removeUnavailableLineItem' => 'orders#removeUnavailableLineItem'
    
    namespace :admin do
      resources :users do
        resources :profiles
        resources :detailed_profiles
        resources :shirt_profiles
        member do
          get 'invite'
        end
      end
    end
  end

end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
Spree::Admin::Orders::CustomerDetailsController.class_eval do

def update

    if @order.update_attributes(order_params)
      if params[:guest_checkout] == "false"
        @order.associate_user!(Spree.user_class.find(params[:user_id]), @order.email.blank?)
      end
      while @order.next; end

      new_profile_id = get_profile_id;

      @order.update_attributes(:payment_known => payment_known)

      old_tax_amount = @order.tax_amount
      new_tax_amount = get_tax_amount

      if(new_tax_amount != nil and new_tax_amount != '')
        new_tax_amount = new_tax_amount.to_d
        #use tax amount instead of tax rate
        if(old_tax_amount != new_tax_amount)
          @order.update_attributes(:tax_amount => new_tax_amount)
          add_custom_tax_amount
        end
      end

      order_id = @order.id

      @line_item = Spree::LineItem.where(:order_id => order_id)
      @line_item.each do |item|
        item.update(profile_id: new_profile_id)
      end

      #This method is causing data loss for table spree_inventory_units.
      #So this is disabled for now until we figure out what's the reason.
      #@order.refresh_shipment_rates
      flash[:success] = Spree.t('customer_details_updated')
      redirect_to admin_order_customer_path(@order)
    else
      render :action => :edit
    end
  end
  
  def add_custom_tax_amount
    if(@order.tax_amount != nil)
       taxAdjustment = Spree::Adjustment.find_by(
          :source_id => @order.id,
          :adjustable_id => @order.id,
          :adjustable_type => "Spree::Order"
          )

        #If custom-tax adjustment already exists, delete it.
        if(taxAdjustment != nil)
          taxAdjustment.destroy
        end

        #apply new tax amount adjustment to order
        amount = @order.tax_amount

        #create custom-tax-amount adjustment
        Spree::Adjustment.create(
          amount: amount,
          order: @order,
          adjustable: @order,
          source: @order,
          label: "Custom tax amount"
        )
      end
      reload_totals
  end

 def reload_totals
    order_updater = Spree::OrderUpdater.new(@order)
    order_updater.update_item_count
    order_updater.update_item_total
    order_updater.update_adjustment_total
    order_updater.persist_totals
    @order.reload
  end

  private

  def order_params
    if (skip_shipping_address.to_i == 1)
      params.require(:order).permit(
      :email
     )
    else
      params.require(:order).permit(
      :email,
      #Manual orders will not have billing address as mentioned by Dan
      #:use_billing,
      #:bill_address_attributes => permitted_address_attributes,
      :ship_address_attributes => permitted_address_attributes
    )
    end
  end

  def get_profile_id
    params['profile_id']
  end

  def get_tax_amount
    params['tax_amount']
  end

  def skip_shipping_address
    params['skip_address']
  end

  def payment_known
    if (params['payment_unknown'].to_i == 1)
      false
    else
      true
    end
  end

end

app/views/spree/admin/orders/_add_product.html.erb
<%= render :partial => "spree/admin/variants/autocomplete", :formats => :js %>
<%= render :partial => "spree/admin/variants/autocomplete_stock", :formats => :js %>

<div id="add-line-item" data-hook>
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:add_product) %></legend>
    
    <div data-hook="add_product_name" class="fullwidth" >
      <%= label_tag :add_variant_id, Spree.t(:name_or_sku) %>
      <div align="right" style="padding:0px;margin: 0px">
      <%= check_box_tag 'custom_shirt' %> <%= label_tag 'custom_shirt', Spree.t(:custom_shirt) %>
      </div>
      <%= hidden_field_tag :add_variant_id, "", :class => "variant_autocomplete fullwidth" %>
    </div>

  </fieldset>

  <div id="stock_details"></div>
</div>

app/views/spree/admin/orders/_form.html.erb
<% customer = Spree::User.find_by(:id => @order.user_id)%>


<fieldset class="no-border-top">
<div data-hook="admin_order_form_fields">
	<div id="select-customer">
  		<fieldset class="no-border-bottom">
    		<legend align="center"><%= Spree.t(:add_customer) %></legend>
				<%= hidden_field_tag :customer_search,  nil, :class => 'alpha thirteen columns' %>
				<%= render :partial => "spree/admin/orders/customer_details/autocomplete", :formats => :js %>
				<a class="button fa fa-plus" href="users/new" icon="plus" >New customer</a>
  		</fieldset>
	</div>


	<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
		<fieldset class="index no-border-bottom" data-hook="customer_guest">
    		<legend align="center"><%= Spree.t(:customer_details) %></legend>
            <% customer = Spree::User.find_by(:id => @order.user_id)%>

			<%if @order.email != nil
				customer_email = @order.email
	 		else
	 			customer_email = ""
	 		end%>

          <%if(customer != nil)%>
	          <% if(customer.first_name == nil) %>
	                <% customer.first_name = "N/A"%>
	          <%end%>

	          <% if(customer.last_name == nil) %>
	              <% customer.last_name = "N/A"%>
	          <%end%>
				<div class="alpha eight columns">
					<div class="field">
						<label>Customer Name:</label>
	                    <label><h3><%=  customer.first_name + " " +  customer.last_name%></h3></label>
					</div>
				</div>
          <%end%>

        <div data-hook="customer_fields" class="row" id = "show_profile" >
            <div class="alpha four columns">
              <div class="field">
              <label>Select Measurement Profile</label><br>
              <% measurement_profiles = {}
                order_profile_id = 1 %>
              <%if (@order.profile_id != nil )
                order_profile_id = @order.profile_id
              end%>
              <%if(customer != nil)
                profiles = Profile.where(:user_id => customer.id)
                profiles.each do |p|
                  measurement_profiles.merge!(p.name => p.id)
                end
              end%>
              <%= select_tag :profile_id, options_for_select(measurement_profiles, order_profile_id), {:class => 'omega three columns', :style=>"margin-left:0px;background-color:white"} %>
              </div>
            </div>
              <%if customer %>
                  <input type="text" class="hidden" id="customer_link_id" value="<%= customer.id %>">
              <% end %>
            <div class="alpha four columns" style="padding-top:20px;padding-left:0px">
              <div class="field">
                <a id="add_profile"  icon="plus" > Create New Measurement Profile</a>
                <span id="add_profile_span"></span>
              </div>
            </div>
            <div class="alpha five columns" style="padding-top:20px;padding-left:0px">
              <div class="field">
                <a id="add_body_profile"  icon="plus" > Create New Body Measurement Profile </a>
              </div>
            </div>
        </div>

		<div class="alpha eight columns">
          <div class="field">
			<%= f.email_field :email, :class => 'alpha eight columns', :value => customer_email, :placeholder => "Enter Email" %>
          </div>
		</div>

        <div class="omega eight columns" style="margin-top:-15px">
			<div class="field">
				<%= label_tag nil, Spree.t(:guest_checkout) %>
				<ul>
					<% if @order.completed? %>
					<li>
						<%= @order.user.nil? ? Spree.t(:say_yes) : Spree.t(:say_no) %>
					</li>
					<% else %>
					<% guest = @order.user.nil? %>
					<li>
						<%= radio_button_tag :guest_checkout, true, guest %>
						<%= label_tag :guest_checkout_true, Spree.t(:say_yes) %>
					</li>
					<li>
						<%= radio_button_tag :guest_checkout, false, !guest, :disabled => @order.cart? %>
						<%= label_tag :guest_checkout_false, Spree.t(:say_no) %>
					</li>
					<%= hidden_field_tag :user_id, @order.user_id %>
					<% end %>
				</ul>
			</div>
		</div>

        </fieldset>

		<div data-hook="ship_address_wrapper">
			<fieldset class="no-border-bottom">
				<legend align="center">
					<%= Spree.t(:shipping_address) %>
				</legend>
				<div align="right">
					<span data-hook="skip_address"> <%= check_box_tag 'skip_address' %>
	                  <%= label_tag 'skip_address', Spree.t(:skip_address) %>
					</span>
	          	</div>
				<%= f.fields_for :ship_address do |sa_form| %>
					<%= render :partial => 'spree/admin/shared/address_form', :locals => { :f => sa_form, :type => 'shipping' } %>
				<% end %>
			</fieldset>
		</div>

		<% content_for :head do %>
			<%= javascript_include_tag 'spree/backend/address_states.js' %>
		<% end %>


	<%= render :partial => 'add_product' if can?(:update, @order) %>

<% if @order.line_items.empty? %>
  <div class="no-objects-found">
    <%= Spree.t(:your_order_is_empty_add_product)%>
  </div>
<% end %>

  <% if @line_item.try(:errors).present? %>
    <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
  <% end %>

  <% if Spree::Order.checkout_step_names.include?(:delivery) %>
    <%= render :partial => "spree/admin/orders/shipment", :collection => @order.shipments, :locals => { :order => @order } %>
  <% else %>
    <%= render :partial => "spree/admin/orders/line_items", :locals => { :order => @order } %>
  <% end %>

	<fieldset class="no-border-bottom">
   		<legend align="center" class="ship-address-title">
			<%= Spree.t(:payment_details) %>
		</legend>
		<span data-hook="payment_unknown" class="omega twelve columns">
			<%= check_box_tag 'payment_unknown', '1', !@order.payment_known %>
			<%= label_tag 'payment_unknown', Spree.t(:payment_unknown) %>
		</span>
		<% if can?(:index, Spree::Payment) %>
        	<%= link_to_with_icon 'credit-card', Spree.t(:payments), admin_order_payments_url(@order), :id=>"payment-link"%>
    	<% end %>
		<%if @order.payment_known%>
			<div class="field tax_rate_label">
				<input type="number" id="tax_amount" name="tax_amount" <%if @order.tax_amount != nil%>value="<%=@order.tax_amount.to_s%>"<%end%>, placeholder= "Enter tax amount" >
			</div>
		<%end%>

   </fieldset>

	<fieldset class="no-border-bottom">
		<legend align="center" class="ship-address-title">
			<%= Spree.t(:add_adjustments) %>
		</legend>
	    <div data-hook="admin_adjustment_form_fields">

			<div class="alpha four columns" style="padding-top:5px">
				<%= number_field  :adjustment, :amount, :class => 'fullwidth', id: 'adjustment_amount', :placeholder => "Amount"%>
			</div>
			<div class="omega eleven columns" style="padding-top:5px">
				<%= text_field :adjustment, :label, :class => 'fullwidth', id: 'adjustment_text', :placeholder => "Description" %>
			</div>

			<table class="omega one columns">
				<tbody>
					<td class="actions">
					<%= link_to '', '#', :class => 'add-adjustment no-text fa fa-plus icon_link with-tip', :data => {'order-number' => @order.number, :action => 'add_adjustment'}, :title => "Add new adjustment" %>
				</td>
				</tbody>
			</table>
		</div>
	</fieldset>

  <%= render :partial => "spree/admin/orders/adjustments", :locals => {
        :adjustments => @order.line_item_adjustments,
        :order => @order,
        :title => Spree.t(:line_item_adjustments)
   } %>
  <%= render :partial => "spree/admin/orders/adjustments", :locals => {
        :adjustments => @order.shipment_adjustments,
        :order => @order,
        :title => Spree.t(:shipment_adjustments)
   } %>
  <%= render :partial => "spree/admin/orders/adjustments", :locals => {
        :adjustments => @order.adjustments,
        :order => @order,
        :title => Spree.t(:order_adjustments)
   } %>

	<div>
		Set Order Date: <%= select_date @order.offline_order_date || Date.today, prefix: :offline_order_date %>
	</div>

  <%= render :partial => "spree/admin/orders/order_summary", :locals => {
        :order => @order,
        :title => Spree.t(:order_summary)
   } %>

  <% if @order.line_items.exists? %>
    <fieldset class="no-border-bottom" id="order-total" data-hook="order_details_total">
      <legend><%= Spree.t(:order_total) %></legend>
      <span class="order-total"><%= @order.display_total %></span>
    </fieldset>
  <% end %>

  	<div class="form-buttons filter-actions actions" data-hook="buttons">
		<%= button Spree.t('actions.update'), 'refresh' %>
	</div>

  <%= javascript_tag do -%>
    var order_number = '<%= @order.number %>';
    var shipments = [];

    <% @order.shipments.each do |shipment| %>
      shipments.push(<%== shipment.to_json(:root => false, :include => [:inventory_units, :stock_location]) %>);
    <% end %>

    <%= render :partial => 'spree/admin/shared/update_order_state', :handlers => [:js] %>
  <% end -%>
</div>
</fieldset>

app/views/spree/admin/orders/edit.html.erb
<% content_for :page_actions do %>
  <% if can?(:fire, @order) %>
    <li><%= event_links %></li>
  <% end %>
  <% if can?(:resend, @order) %>
    <li><%= button_link_to Spree.t(:resend), resend_admin_order_url(@order), :method => :post, :icon => 'email' %></li>
  <% end %>
  <% if can?(:admin, Spree::Order) %>
    <li><%= button_link_to Spree.t(:back_to_orders_list), admin_orders_path, :icon => 'arrow-left' %></li>
  <% end %>
  <% content_for :page_title do %>
  <%= link_to "#{Spree.t(:order)} ##{@order.number}", spree.edit_admin_order_path(@order) %>
<% end %>
<% end %>

<%#= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<div data-hook="admin_order_edit_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
</div>

<% if @order.payments.exists? && @order.considered_risky? %>
  <%= render 'spree/admin/orders/risk_analysis', latest_payment: @order.payments.order("created_at DESC").first %>
<% end %>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= form_for @order, :url => admin_order_url(@order) do |f| %>
	  <%= render 'form', :f => f %>
	<% end %>
  </div>
</div>

<% content_for :head do %>
  <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_orders) %>
<% end %>

<% content_for :page_actions do %>
  <li>
	<%= button_link_to Spree.t(:new_order), new_admin_order_url, :icon => 'plus', :id => 'admin_new_order' %>
  </li>
  <li>
    	<%= button_link_to Spree.t(:Historical_order), admin_historical_orders_show_url, :icon => 'plus', :id => 'admin_historical_orders' %>
  </li>
<% end if can? :edit, Spree::Order.new %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="field-block alpha four columns">
        <div class="date-range-filter field">
          <%= label_tag nil, Spree.t(:date_range) %>
          <div class="date-range-fields">
            <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start) %>

            <span class="range-divider">
              <i class="fa fa-arrow-right"></i>
            </span>

            <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop) %>
          </div>
        </div>

        <div class="field">
          <%= label_tag nil, Spree.t(:status) %>
          <%= f.select :state_eq, Spree::Order.state_machines[:state].states.collect {|s| [Spree.t("order_state.#{s.name}"), s.value]}, {:include_blank => true}, :class => 'select2' %>
        </div>

      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag nil, Spree.t(:order_number, :number => '') %>
          <%= f.text_field :number_cont %>
        </div>
        <div class="field">
          <%= label_tag nil, Spree.t(:email) %>
          <%= f.text_field :email_cont %>
        </div>
      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag nil, Spree.t(:first_name_begins_with) %>
          <%= f.text_field :bill_address_firstname_start, :size => 25 %>
        </div>
        <div class="field">
          <%= label_tag nil, Spree.t(:last_name_begins_with) %>
          <%= f.text_field :bill_address_lastname_start, :size => 25%>
        </div>
      </div>

      <div class="omega four columns">
        <div class="field checkbox">
          <label>
            <%= f.check_box :completed_at_not_null, {:checked => @show_only_completed}, '1', '0' %>
            <%= Spree.t(:show_only_complete_orders) %>
          </label>
        </div>
        <div class="field">
          <%= label_tag nil, Spree.t(:promotion) %>
          <%= f.select :promotions_id_in, Spree::Promotion.all.collect {|p| [p.name, p.id]}, {:include_blank => true}, :class => 'select2' %>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button Spree.t(:filter_results), 'search' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @orders %>

<% if @orders.any? %>
  <table class="index responsive" id="listing_orders" data-hook>
    <colgroup>
       <col style="width: 13%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 12%;">
       <% if Spree::Order.checkout_step_names.include?(:delivery) %>
         <col style="width: 12%;">
       <% end %>
       <col style="width: 25%;">
       <col style="width: 10%;">
       <col style="width: 8%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at, I18n.t(:completed_at, :scope => 'activerecord.attributes.spree/order') %></th>
        <% else %>
          <th><%= sort_link @search, :created_at,   I18n.t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th><%= sort_link @search, :number,         I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :state,          I18n.t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :payment_state,  I18n.t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>
         <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th><%= sort_link @search, :shipment_state, I18n.t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>
         <% end %>
        <th><%= sort_link @search, :email,          I18n.t(:email, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :total,          I18n.t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td class="align-center"><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
        <td class="align-center"><%= link_to order.number, show_admin_order_path(order) %></td>
        <td class="align-center"><span class="state <%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span></td>
        <td class="align-center"><span class="state <%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></span></td>
          <% if Spree::Order.checkout_step_names.include?(:delivery) %>
            <td class="align-center"><span class="state <%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") if order.shipment_state %></span></td>
          <% end %>
        <td><%= mail_to order.email %></td>
        <td class="align-center"><%= order.display_total.to_html %></td>
        <td class='actions align-center' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
        </td>
        <td class="actions">
         <%= link_to '', '/admin/orders/'+ order.number.to_s + '/show', :class => 'show-order icon_link fa fa-folder-open-o no-text with-tip', :title => Spree.t('show') %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/order')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_order_path %>!
  </div>
<% end %>

<%= paginate @orders %>