config/routes.rb
Sartor::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
    resources :appointment_contacts

    resources :profiles
    resources :simple_profiles
    resources :detailed_profiles
    resources :shirt_profiles

    resources :ja_giftsets

    get '/privacy', :to => "info#privacy"
    get '/terms', :to => "info#terms_of_service"
    get '/shipping', :to => "info#shipping"
    get '/returns', :to => "info#returns"
    get '/about_sartor', :to => "info#about_sartor"
    get '/perscholas', :to => "info#per_scholas"
    get '/mygift', :to => "info#mygift"

    get '/password/change' => 'user_passwords#edit', :as => :simple_edit_password

    post '/shirts-shirtconfig' => 'products#shirtConfigSession'
    get '/shirts' => 'products#index_shirts'
    post '/shirts-filter' => 'products#filtered_shirts'
    post '/shirts-tabs-click' => 'products#shirtresponse'
    post '/shirts-collections' => 'products#shirts_collections'
    post '/shirts-usual-style' => 'your_usual#add'
    get '/ties' => 'products#index_ties'

    get '/johnallans' => 'ja_giftsets#new'

    get '/products/show_no_tie'

    get '/gifting' => 'virtual_gift_cards#new'
    post '/gifting' => 'virtual_gift_cards#create'
    get  '/admin/users/virtual_gift_cards' => "admin/gift_cards#index", :as => :admin_virtual_gift_cards
    get  '/admin/users/:id/virtual_gift_cards/' => "admin/gift_cards#show", :as => :admin_virtual_gift_card
    post '/admin/users/redeem_gift_cards/' => "admin/gift_cards#redeem_gift_cards_complete"
    get '/admin/users/:id/redeem_gift_cards/' => "admin/gift_cards#redeem_gift_cards", :as => :admin_redeem_gift_cards
    post '/user/redeem-gift-cards' => 'users#redeem_gift_cards'

    put '/api/shipments/:id/update_item' => "api/shipments#update_item", :defaults => { :format => 'json' }
    get '/admin/orders/:id/detail_profile' => "admin/detailed_profiles#new"
    get '/admin/orders/:id/users/new' =>  "admin/users#new"
    get '/admin/orders/:id/show' => "admin/orders#show", :as => :show_admin_order
    put '/admin/orders/:id/show' => "admin/orders#show", :as => :show_admin_order_put
    put '/admin/orders/:id/save-jobs' =>  "admin/show_mockup#save_jobs_to_line_items"
    put '/admin/orders/:id/update-shirt-status' =>  "admin/show_mockup#update_shirt_status"
    put '/admin/orders/:id/add-tracking-number' =>  "admin/show_mockup#add_tracking_number"
    put '/api/shipments/:id/delete_line_item' => "api/shipments#delete_line_item", :defaults => {:format=>"json"}
    get '/admin/update-stocks' => "admin/stock_locations#update_stocks_for_all_products", :as => :update_stocks
    post '/admin/admin-get-measurements' => "admin/create_shirt#create_my_shirt"

    post '/admin/read_csv' => "admin/csv_uploaders#read_csv"
    get '/admin/csv/show' => "admin/csv_uploaders#show", :as => :admin_csv_show
    get '/admin/historical_orders' => "admin/historical_orders#show", :as => :admin_historical_orders_show
    post '/admin/historical_order_csv' => "admin/historical_orders#import_historical_orders"
    get '/admin/csv/notify' => "admin/csv_uploaders#notify", :as => :admin_import_notify
    
    get '/wishlist/refer_to_friend/:id' => "wishlist_mailer#email_form", :as => :wishlist_email_to_friend
    post '/wishlist/refer_to_friend/' => "wishlist_mailer#send_mail"
    post '/update_wished_products' => 'wished_products#update_wished_product'    

    get '/referral/referral_url_to_friend/:link' => "referral_mailer#email_form", :as => :referral_url_email_to_friend
    post '/referral/referral_url_to_friend/' => "referral_mailer#send_mail"

    get '/account/orders' => 'users#show_orders'
    get '/account/history' => 'users#show_history'
    get '/account/address' => 'users#show_address'
    get '/account/sartor-wardrobe' => 'users#sartor_wardrobe'
    get '/account/loyalty' => 'users#loyalty_points'
    get '/account/redeem' => 'users#redeem_cards'
    post '/shirt/wardrobe' => 'wardrobes#show', :as => :show_wardrobe

    get '/sartor_office' => 'appointment_contacts#sartor_office'
    get '/office_visit' => 'appointment_contacts#office_visit'

    get '/contact' => 'contact_us#show'
    post '/contact' => 'contact_us#create'

    get '/get-detailedProfile' => 'shirt_profiles#get_detailed_profile'
    post '/generate-measurements' => 'shirt_profiles#createnewmeasurements'

    post '/removeUnavailableLineItem' => 'orders#removeUnavailableLineItem'
    
    namespace :admin do
      resources :users do
        resources :profiles
        resources :detailed_profiles
        resources :shirt_profiles
        member do
          get 'invite'
        end
      end
    end
  end

end

app/models/spree/appointment_contact.rb
module Spree
  class AppointmentContact < ActiveRecord::Base

    # attr_accessor :email, :phone, :message, :name, :location_type, :address
    
    LOCATION_TYPES = ["Home", "Work", "Other"]

    EMAIL_REGEX = /\A
      [^\s@]+ # non-at-sign characters, at least one
        @     # at-sign
      [^\s.@] # non-at-sign and non-period character
      [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
       \.     # period
      [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
      [^\s.@] # non-at-sign and non-period character
    \z/x

    validates :email,   :format => { :with => EMAIL_REGEX },
                        :presence => true
    validates :message, :presence => true
    validates :name,    :presence => true

    #def initialize(attributes = {})
    #  [:email, :message, :name, :subject].each do |attribute|
    #    self.send("#{attribute}=", attributes[attribute]) if attributes and attributes.has_key?(attribute)
    #  end
    #end

    # def save
    #   if self.valid?
    #     Spree::ContactUs::ContactMailer.contact_email(self).deliver
    #     return true
    #   end
    #   return false
    # end

  end
end

app/models/spree/calculator.rb
module Spree
  class Calculator < ActiveRecord::Base
    belongs_to :calculable, polymorphic: true  

    # This method calls a compute_<computable> method. must be overriden in concrete calculator.
    #
    # It should return amount computed based on #calculable and the computable parameter
    def compute(computable)
      # Spree::LineItem -> :compute_line_item
      computable_name = computable.class.name.demodulize.underscore
      method = "compute_#{computable_name}".to_sym
      calculator_class = self.class
      if respond_to?(method)
        self.send(method, computable)
      else
        raise NotImplementedError, "Please implement '#{method}(#{computable_name})' in your calculator: #{calculator_class.name}"
      end
    end

    # overwrite to provide description for your calculators
    def self.description
      'Base Calculator'
    end

    ###################################################################

    def self.register(*klasses)
    end

    # Returns all calculators applicable for kind of work
    def self.calculators
      Rails.application.config.spree.calculators
    end

    def to_s
      self.class.name.titleize.gsub("Calculator\/", "")
    end

    def description
      self.class.description
    end

    def available?(object)
      true
    end
  end
end

app/models/spree/gift_card.rb
require 'spree/core/validators/email'

module Spree
  class GiftCard < ActiveRecord::Base

    UNACTIVATABLE_ORDER_STATES = ["complete", "awaiting_return", "returned"]

    belongs_to :variant
    belongs_to :line_item

    has_many :transactions, class_name: 'Spree::GiftCardTransaction'

    # validates :code,               presence: true, uniqueness: true
    validates :current_value,      presence: true
    # validates :email, email: true, presence: true
    # validates :name,               presence: true
    validates :original_value,     presence: true

    after_create :generate_code   #, on: :create
    before_validation :set_calculator, on: :create
    before_validation :set_values, on: :create

    include Spree::Core::CalculatedAdjustments

    def apply(order)
      # Nothing to do if the gift card is already associated with the order
      return if order.gift_credit_exists?(self)
      order.update!
      Spree::Adjustment.create!(
            amount: compute_amount(order),
            order: order,
            adjustable: order,
            source: self,
            mandatory: true,
            label: "#{Spree.t(:gift_card)}"
          )

      order.update!
    end

    # Calculate the amount to be used when creating an adjustment
    def compute_amount(calculable)
      self.calculator.compute(calculable, self)
    end

    def debit(amount, order)
      raise 'Cannot debit gift card by amount greater than current value.' if (self.current_value - amount.to_f.abs) < 0
      transaction = self.transactions.build
      transaction.amount = amount
      transaction.order  = order
      self.current_value = self.current_value - amount.abs
      self.save
    end

    def price
      self.line_item ? self.line_item.price * self.line_item.quantity : self.variant.price
    end

    def order_activatable?(order)
      order &&
      created_at < order.created_at &&
      current_value > 0 &&
      !UNACTIVATABLE_ORDER_STATES.include?(order.state)
    end

    private

    def generate_code  # TODO move this to private after switch back to calling from callback
      return if self.code.present?
      until self.code.present? && self.class.where(code: self.code).count == 0
        self.code = "#{1000 + self.id}-" + ('A'..'Z').to_a.shuffle[0,4].join
      end
      #self.save -- needed when called from callback
      self.save
    end

    def set_calculator
      self.calculator = Spree::Calculator::GiftCard.new
    end

    def set_values
      self.current_value  = self.variant.try(:price)
      self.original_value = self.variant.try(:price)
    end

  end
end

app/models/spree/image_decorator.rb
module Spree
  Image.class_eval do
    
    has_attached_file :attachment,
                  styles: { mini: '48x96>', small: '100x200>', product: '240x480>', large: '400x800>',
                   huge: '1200x2400', :'mini@2x' => '96x192>', :'small@2x' => '200x400>', :'product@2x' => '480x960>',
                    :'large@2x' => '1200x2400>', :'huge@2x' => '2400x4800' },
                  default_style: :product,
                  url: '/spree/products/:id/:basename-:style.:extension',
                  path: ':rails_root/public/spree/products/:id/:basename-:style.:extension',
                  convert_options: { all: '-strip -auto-orient' }
                  
  end
end

app/models/spree/item_adjustments_decorator.rb
Spree::ItemAdjustments.class_eval do
  def update_adjustments

    sartor_discount = 0
    promo_total = 0
    included_tax_total = 0
    additional_tax_total = 0

    run_callbacks :promo_adjustments do
      promotion_total = adjustments.promotion.reload.map(&:update!).compact.sum
      unless promotion_total == 0
        choose_best_promotion_adjustment
      end
      promo_total = best_promotion_adjustment.try(:amount).to_f
    end

    #When 'item' is an order
    if (item.class.to_s == "Spree::Order")
      order = item
      #Do not include spree tax mechanism if order is a manual order
      if (order.manual_order == false)
        run_callbacks :tax_adjustments do
          tax = (item.respond_to?(:all_adjustments) ? item.all_adjustments : item.adjustments).tax
          included_tax_total = tax.included.reload.map(&:update!).compact.sum
          additional_tax_total = tax.additional.reload.map(&:update!).compact.sum
        end
      else
        taxAdjustment = Spree::Adjustment.find_by(
          :source_id => order.id,
          :adjustable_id => order.id,
          :adjustable_type => "Spree::Order"
        )
        if (taxAdjustment != nil)
          additional_tax_total = taxAdjustment.amount
        end
      end
    else if (item.class.to_s == "Spree::LineItem")
        #When 'item' is a line item
        order = Spree::Order.find_by(:id => item.order_id)
        custom_adjustments = adjustments.where(:source_type  => 'Spree::LineItem', :source_id => item.id);
        custom_adjustments.each do |a|
          sartor_discount = sartor_discount + a.amount
        end
        if (order.manual_order == false)
          run_callbacks :tax_adjustments do
            tax = (item.respond_to?(:all_adjustments) ? item.all_adjustments : item.adjustments).tax
            included_tax_total = tax.included.reload.map(&:update!).compact.sum
            additional_tax_total = tax.additional.reload.map(&:update!).compact.sum
          end
        end
      else
      #When 'item' is a shipment
        order = Spree::Order.find_by(:id => item.order_id)

        if (order.manual_order == false)
          run_callbacks :tax_adjustments do
            tax = (item.respond_to?(:all_adjustments) ? item.all_adjustments : item.adjustments).tax
            included_tax_total = tax.included.reload.map(&:update!).compact.sum
            additional_tax_total = tax.additional.reload.map(&:update!).compact.sum
          end
        end
      end
    end

    item.update_columns(
      :promo_total => promo_total,
      :included_tax_total => included_tax_total,
      :additional_tax_total => additional_tax_total,
      :adjustment_total => promo_total + additional_tax_total + sartor_discount,
      :updated_at => Time.now,
    )
  end
end

app/models/spree/line_item_decorator.rb
Spree::LineItem.class_eval do

  belongs_to :profile
  has_one :shirt_configuration

  has_many :sub_lineitems, class_name: "Spree::LineItem",
                          foreign_key: "parent_lineitem_id"

  belongs_to :parent_lineitem, class_name: "Spree::LineItem"
  
  def update_tax_charge
    if (order.manual_order == false) #If order is a manual order, do not use spree taxes.
      Spree::TaxRate.adjust(order, [self])
    end
  end

end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

  def create_tax_charge!
    #Do not calculate taxes if order is a manual order
    if (self.manual_order == false)
      Spree::TaxRate.adjust(self, line_items)
      Spree::TaxRate.adjust(self, shipments) if shipments.any?
    end
  end
  
  def display_custom_tax_total
    Spree::Money.new(tax_amount, { currency: currency })
  end
  
  def display_tax_total
    Spree::Money.new(included_tax_total + additional_tax_total + (tax_amount || 0), { currency: currency })
  end

  #This was done to fix the bug related to getting wrong stock location...
  #...while adding the first product in the order
  def create_proposed_shipments
      if(self.manual_order == false)
        adjustments.shipping.delete_all
        shipments.destroy_all

        packages = Spree::Stock::Coordinator.new(self).packages
        packages.each do |package|
          shipments << package.to_shipment
        end
      end
      shipments
   end
   
    def deliver_order_confirmation_email
      Spree::OrderMailer.confirm_email(self.id).deliver
      update_column(:confirmation_delivered, true)
      send_gift_card_mail
    end
    
    def send_gift_card_mail
      line_items.each do |item|
        if item.gift_card
          virtual_gift_cards_details = VirtualGiftCardsDetails.find_by(
            :line_item_id => item.id
          )
          virtual_gift_card = Spree::VirtualGiftCard.find_by(
            :line_item_id => item.id
          )
          if virtual_gift_cards_details.card_type == "virtual"
            Spree::VirtualGiftCardsMailer.send_redemption_code(virtual_gift_cards_details, virtual_gift_card, item.order.user_id).deliver  
          end
        end
      end
    end
end

app/models/spree/order_populator.rb
module Spree
  class OrderPopulator
    attr_accessor :order, :currency
    attr_reader :errors

    def initialize(order, currency)
      @order = order
      @currency = currency
      @errors = ActiveModel::Errors.new(self)
    end

    def populate(variant_id, profile_id, shirt_configuration, quantity)
      attempt_cart_add(variant_id, profile_id, shirt_configuration, quantity)
      order.ensure_updated_shipments
      valid?
    end

    def valid?
      errors.empty?
    end

    private

    def attempt_cart_add(variant_id, profile_id, shirt_configuration, quantity)
      quantity = quantity.to_i
      # 2,147,483,647 is crazy.
      # See issue #2695.
      if quantity > 2_147_483_647
        errors.add(:base, Spree.t(:please_enter_reasonable_quantity, :scope => :order_populator))
        return false
      end
      variant = Spree::Variant.find(variant_id)
      if quantity > 0
        line_item = @order.contents.add(variant, quantity, currency, nil, 0, "", profile_id)
        line_item.shirt_configuration = shirt_configuration
        
        unless line_item.valid?
          errors.add(:base, line_item.errors.messages.values.join(" "))
          return false
        end
      end
    end
  end
end

app/models/spree/payment_decorator.rb
Spree::Payment.class_eval do
#  before_update :send_gift_card, :if => "state_changed? && state_was != 'completed' && state == 'completed'"

#  def send_gift_card
#    order.line_items.each do |li|
#      Spree::OrderMailer.gift_card_email(li.gift_card.id, order).deliver if li.gift_card
#    end
#  end
end

app/models/spree/promotion_handler/cart_decorator.rb
Spree::PromotionHandler::Cart.class_eval do
  
  def activate
    promotions.each do |promotion|
      if (line_item && promotion.eligible?(line_item)) || promotion.eligible?(order)
        promotion.activate(line_item: line_item, order: order, current_promotion: promotion)
      end
    end
  end
end

app/models/spree/promotion_rule_decorator.rb
Spree::PromotionRule.class_eval do
  # This states if a promotion can be applied to the specified line item
    # It is true by default, but can be overridden by promotion rules to provide conditions
    def actionable?(line_item)
      true
    end
end

app/views/spree/users/_account_sidebar.html.erb
<div id="account_side_bar_main" class="account-side-bar-collapse row">
  <div id="demo" class="account-side-bar account-side-bar-collapse-slider">
    <nav class="menu">
          <ul data-hook="account_side_bar" style="padding-left: 0px;">
            <li<%== ' class="account-side-bar-active"' if current == 'Account' %>>
              <a class="btn full-width small" href="/account">Account Info</a>
            </li>
<!-- 
            <li<%== ' class="account-side-bar-active"' if current === 'Measurement Profile' %>>
            <%= link_to "Measurement Profile", profiles_path,:class => "btn full-width small"%>
            </li> 
 -->
           <!-- <li<%== ' class="account-side-bar-active"' if current == 'Account address' %>>
              <a class="btn full-width small" href="/account/address">Shipping Profile</a>
            </li>-->

            <li<%== ' class="account-side-bar-active"' if current == 'Account orders' %>>
              <a class="btn full-width small" href="/account/orders">Order History</a>
            </li>

            <li<%== ' class="account-side-bar-active"' if current == 'Account history' %>>
              <a class="btn full-width small" href="/account/history">Store Credits</a>
            </li>

            <!--
            <li<%== ' class="account-side-bar-active"' if current == 'loyalty points' %>>
              <a class="btn btn-default btn-sm" href="/account/loyalty">Loyalty Points</a>
            </li>-->


          <li<%== ' class="account-side-bar-active"' if current == 'redeem card' %>>
              <a class="btn full-width small" href="/account/redeem">Redeem Gift Cards</a>
            </li>

        </ul>
    </nav>
  </div>

</div>

app/views/spree/users/_edit.html.erb
<div class="row account-side-content">
  <div class="span2"></div>
	<div class="account-info-label">
		<div class="page-title">
			<h1>Account Info</h1>
		</div>
		<br>
	</div>
  <div class="account-info-section" >
		<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @spree_user } %>
			<%= simple_form_for @user, :url => spree.user_path(@user), :method => :put, :html => {:class => 'form-horizontal'} do |f| %>
    		<%= render :partial => 'spree/shared/user_form', :locals => { :f => f } %>
				<div class="control-group">
			    	<div class="col-lg-6 col-lg-offset-6 controls-measurement-profiles">
            <a class="btn btn-custom-black" href="/account" id="close_button">cancel</a>
			     	<%= f.submit 'Save', :class => 'btn btn-custom' %>
					</div>
				</div>
		<% end %>
	</div>
</div>

app/views/spree/users/_profiles.html.erb
<table>
	<colgroup>
	      <col style="width: 74%;" />
	      <col style="width: 13%;" />
	      <col style="width: 13%;" />
    	</colgroup>
	<thead>
		<th></th>
		<th></th>
		<th></th>
	</thead>
	<tbody>
	<% @profiles.each do |profile| %>
	<tr>
		<td><%= profile.name %></td>
		<td><%= link_to 'Edit', edit_profile_path(profile) %></td>
		<td> <%= link_to 'Delete', [profile], method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	</tbody>
	<% end %>
</table>

app/views/spree/users/loyalty_points.html.erb
<div class="row">
	<div id="account_side_bar_border" class="col-lg-3 col-md-4 col-sm-4">
		<%= render "account_sidebar", :current => 'loyalty points' %>
	</div>
	<div id="divwidth" class="col-lg-9 col-md-8 col-sm-8" style="padding-top:10px;">
	    <div class="user_loyalty_point_section">
	    	<h3><%= Spree.t(:loyalty_points_balance) %>
				:&nbsp;<%= @user.loyalty_points_balance %>
			<h3>
	    </div>
	</div>
</div>

app/views/spree/users/redeem_cards.html.erb
<div class="row">
  <div class="row hidden-sm hidden-md hidden-lg" id="command-row">
      <div class="col-xs-6">
          <button id="side-bar-collapse-btn" type="button" class="btn btn-default btn-command account-info-side-bar-btn" data-toggle="toggle" data-target="#demo">
              <i class="fa fa-gear fa-2x"></i>Settings
          </button>
      </div>
      <div class="col-xs-6 ">
          <a href="/shirts" type="button" class="btn btn-default btn-command pull-right">
              <i class="fa fa-shopping-bag fa-2x"></i>Return To Shop</a>
      </div>
  </div>
  <div id="account_side_bar_border" class="col-lg-3 col-md-4 col-sm-4 ">
    <div class="col-padding">
		<%= render "account_sidebar", :current => 'redeem card' %>
	   </div>
  </div>
	<div id="divwidth" class="col-lg-9 col-md-8 col-sm-8 page-text" style="padding-top:10px;">
     <div class="col-padding">
			<form action="/user/redeem-gift-cards" method="post">
					<input name="utf8" type="hidden" value="" />
					<input name="authenticity_token" type="hidden" value="">
					<label class="my-account-page-header-title"><%= Spree.t(:redeem_gift_card) %></label><br>
					<div class=" col-md-8 col-xs-12 padding-zero " style="padding-right:10px;padding-bottom:10px;">
						<input class="form-control" id="redemption_code" name="redemption_code" required="required" type="text" placeholder="Redemption Code">
					</div>
					<div class=" col-md-4 col-xs-12 padding-zero">
						<button class="btn btn-custom" id="add-to-cart-button" type="submit">
							Redeem
						</button>
					</div>
	  	</form>
      </div>
	 </div>
</div>

app/views/spree/users/show_address.html.erb
<div class="row">
	  <div class="row hidden-sm hidden-md hidden-lg" id="command-row">
      <div class="col-xs-6">
          <button id="side-bar-collapse-btn" type="button" class="btn btn-default btn-command account-info-side-bar-btn" data-toggle="toggle" data-target="#demo">
              <i class="fa fa-gear fa-2x"></i>Settings
          </button>
      </div>
       <div class="col-xs-6">
          <a href="/shirts" type="button" class="btn btn-default btn-command pull-right">
              <i class="fa fa-shopping-bag fa-2x"></i>Return To Shop</a>
      </div>
  </div>
  <div id="account_side_bar_border" class="col-lg-3 col-md-4 col-sm-4">
		<%= render "account_sidebar", :current => 'Account address' %>
	</div>
	<div class="col-lg-9 col-md-8 col-sm-8">

	</div>
</div>

app/views/spree/users/show_history.html.erb
<div class="row ">
  <div class="row hidden-sm hidden-md hidden-lg" id="command-row">
      <div class="col-xs-6">
          <button id="side-bar-collapse-btn" type="button" class="btn btn-default btn-command account-info-side-bar-btn" data-toggle="toggle" data-target="#demo">
              <i class="fa fa-gear fa-2x"></i>Settings
          </button>
      </div>
       <div class="col-xs-6 ">
          <a href="/shirts" type="button" class="btn btn-default btn-command pull-right">
              <i class="fa fa-shopping-bag fa-2x"></i>Return To Shop</a>
      </div>
  </div>
  <div id="account_side_bar_border" class="col-lg-3 col-md-4 col-sm-4">
    <div class="col-padding">
		  <%= render "account_sidebar", :current => 'Account history' %>
    </div>
	</div>
  <div id="divwidth" class="col-lg-9 col-md-8 col-sm-8 page-text" style="padding-top:10px;" >
    <div class="col-padding">
      <% if @user.total_available_store_credit > 0 %>
          <label class="my-account-page-sub-header">Total available store credit: <%= Spree::Money.new(@user.total_available_store_credit) %>.</label>
      <% else %>
          <label class="my-account-page-sub-header">You have no available store credit.</label>
      <% end %>
      <!--
      <h3>"rubytag"= Spree.t(:refer_a_friend) "rubytag"</h3>
      <div class="col-md-8">
      <input type='text' class="form-control" value='"rubytag" referral_url(@user.referral.code) "rubytag"' onClick='this.select();' readonly />
      </div>
      <div class="col-md-4">
      "rubytag" link_to "Send to Friend", referral_url_email_to_friend_url(@user.referral.code), :class => "btn btn-primary" "rubytag"
      </div>
      </br>
      </br>
      <div class="col-md-3">
      "rubytag"= Spree.t(:Referred_users) "rubytag":
      "rubytag"= @user.referred_count"rubytag"
      </div>-->
    </div>
  </div>
</div>

app/views/spree/users/show_orders.html.erb
<div class="row">
  <div class="row hidden-sm hidden-md hidden-lg" id="command-row">
    <div class="col-xs-6">
        <button id="side-bar-collapse-btn" type="button" class="btn btn-default btn-command account-info-side-bar-btn" data-toggle="toggle" data-target="#demo">
            <i class="fa fa-gear fa-2x"></i>Settings
        </button>
    </div>
     <div class="col-xs-6 ">
          <a href="/shirts" type="button" class="btn btn-default btn-command pull-right">
              <i class="fa fa-shopping-bag fa-2x"></i>Return To Shop</a>
      </div>
  </div>
  <div id="account_side_bar_border" class="col-lg-3 col-md-4 col-sm-4">
    <div class="col-padding">
      <%= render "account_sidebar", :current => 'Account orders' %>
    </div>
  </div>
  <div id="divwidth" class="col-lg-9 col-md-8 col-sm-8 page-text" style="padding-top:10px;">
  <div class="col-padding">
    <div class="user_order_history_section">
      <div>
        <label class="my-account-page-header-title">Order History</label>
      </div>
      <% if @orders.present? %>
            <table class="order-summary table">
                  <thead>
                  <tr class="my-account-page-sub-header" style="text-transform:Capitalize;">
                    <th class="order-number">Order <%= I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
                    <th class="order-date">Order <%= Spree.t(:date) %></th>
                    <!--<th class="order-payment-state"><%= Spree.t(:payment_state) %></th>-->
                    <th class="order-total"><%= Spree.t(:total) %></th>
                  </tr>
                  </thead>
                  <tbody>
                        <% @ordersdesc.each do |order| %>
                        <% if order.completed_at != nil
                            if(order.manual_order && order.offline_order_date)
                                completed_date = order.offline_order_date.to_date
                            else
                                completed_date = order.completed_at.to_date
                            end
                        else
                            completed_date = "Incomplete order."
                        end%>
                            <tr class="<%= cycle('even', 'odd') %>">
                            <td class="order-number"><%= link_to order.number, order_url(order) %></td>
                            <td class="order-date"><%= completed_date.strftime("%b %d, %Y") %></td>
                            <!--<td class="order-payment-state"><%= Spree.t("payment_states.#{order.payment_state}").titleize if order.payment_state %></td>-->
                            <td class="order-total"><%= order.display_total %></td>
                            </tr>
                        <% end %>
                  </tbody>
            </table>
      <% else %>
             <p><%= Spree.t(:you_have_no_orders_yet) %></p>
      <% end %>
    </div>
  </div>
  </div>
</div>